### ISSUE TITLE
Does not allow npm version commits

### ISSUE THREAD

**Issue by SomeKittens** [kentcdodds/validate-commit-msg#13]
I'd like at least a flag to allow npm version commits:

> npm ERR! INVALID COMMIT MSG: does not match "<type>(<scope>): <subject>" ! was: 0.6.15

**Comment by kentcdodds** [comment]
I need to give you an apology. For some reason, I want watching this repository so I want getting notifications about issues and pull requests. I am so incredibly sorry. Please forgive me. I really feel awful. I hope my unresponsiveness doesn't hinder you contributing more in the future.

As for your specific pull request, I'll give it a closer look soon.

**Comment by kentcdodds** [comment]
Waiting on @jcollado to respond to my comment on his PR. Thanks for your patience :-)

**Comment by SomeKittens** [comment]
Thanks, Kent!  Greenkeeper.io has informed me that this breaks my build so let me look into this.

**Comment by kentcdodds** [comment]
Thanks!
