### ISSUE TITLE
Question on installation

### ISSUE THREAD

**Issue by JamieMason** [kentcdodds/validate-commit-msg#20]
I think I must be doing something wrong here, I can't get validate-commit-msg to run.

The relevant bits of my package.json are;

```json
{
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    },
    "ghooks": {
      "commit-msg": "validate-commit-msg",
      "pre-commit": "fixpack && npm run lint && npm test"
    },
    "validate-commit-msg": {
      "types": [
        "feat",
        "fix",
        "docs",
        "style",
        "refactor",
        "perf",
        "test",
        "chore",
        "revert"
      ],
      "warnOnFail": false,
      "maxSubjectLength": 100
    }
  },
  "devDependencies": {
    "cz-conventional-changelog": "1.1.5",
    "ghooks": "1.0.3",
    "validate-commit-msg": "2.1.0"
  },
}
```

I run `npm install` etc and example usage is;

```
touch temp.txt
git add .
git commit -m "this message should fail validation"
```

I'd expect the validator to throw, but nothing happens. I added;

```javascript
console.log('hello from validate-commit-msg');
process.exit(1)
```

to the top of `node_modules/validate-commit-msg/index.js` to be sure, but this doesn't appear. While in there I noticed;

```javascript
/**
 * Git COMMIT-MSG hook for validating commit message
 * See https://docs.google.com/document/d/1rk04jEuGfk9kYzfqCuOlPTSJw3hEDZJTBN5E5f1SALo/edit
 *
 * Installation:
 * >> cd <angular-repo>
 * >> ln -s ../../validate-commit-msg.js .git/hooks/commit-msg
 */
```

Am I just missing this installation step? I'm expecting though that ghooks would be handling this part.

Again, pretty sure I'm doing something wrong — can anyone help?

Thanks.

Jamie / [@fold_left](https://twitter.com/fold_left)

**Comment by kentcdodds** [comment]
Hmmm... That comment is dated and should be removed. `ghooks` should install the commit hook for you. My guess is that it's a `ghooks` issue. Does your `pre-commit` hook run?

**Comment by JamieMason** [comment]
Thanks @kentcdodds, I created an isolated test case which _does_ work — so something else is going on in my setup.

Closing, thanks for your help :+1:
