### ISSUE TITLE
Link to angular.md is dead

### ISSUE THREAD

**Issue by dritter** [kentcdodds/validate-commit-msg#21]
Hi there!

The link to the `angular.md` in the project description is dead. It should be https://github.com/ajoslin/conventional-changelog/blob/v0.5.3/conventions/angular.md

**Comment by kentcdodds** [comment]
:+1: yeah, I've had to go around updating a bunch of projects because of that change! Would you like to [makeapullrequest.com](http://makeapullrequest.com)? :-)

**Comment by kentcdodds** [comment]
Actually @dritter, I think this would make a good [first-timers-only](https://medium.com/@kentcdodds/first-timers-only-78281ea47455) issue. Do you mind holding off on making a pull request to give a newbie a chance to try contributing?

**Comment by kentcdodds** [comment]
Oh... :sweat_smile: just realized you're actually talking about the repo meta-data, not anything that can be committed to the repo.... That's been fixed. Thanks!

**Comment by dritter** [comment]
Yep. I meant the repo metadata. :smile: Thx for the quick fix.

**Comment by kentcdodds** [comment]
Thanks for letting me know!
