### ISSUE TITLE
Print entire commit message to console on failure

### ISSUE THREAD

**Issue by erquhart** [kentcdodds/validate-commit-msg#32]
If a developer takes time to write a solid, multiple line commit message, and the message fails the hook, they may lose the message entirely depending on how it was created.

To address this, I propose adding an option (or just changing the default behavior, sans option) to print the entire commit message on failure.

Thoughts?

**Comment by kentcdodds** [comment]
I definitely think this would be handy. I believe it's already supported with [`helpMessage`](https://github.com/kentcdodds/validate-commit-msg#helpmessage). Let me know if that doesn't work for some reason.

**Comment by kentcdodds** [comment]
Sorry, clicked the wrong button. Please close if this resolves the issue!

**Comment by erquhart** [comment]
Yep, you're right, if the placeholder in helpMessage provides all content from multiple line commit messages, then we're good.

**Comment by erquhart** [comment]
@kentcdodds nope, looks like that placeholder only prints the first line of the commit message.

**Comment by kentcdodds** [comment]
Sad day. Well, feel free to [makeapullrequest.com](http://makeapullrequest.com). Let me know if you need any direction.

**Comment by erquhart** [comment]
Nice work @Emmurillo! Closing.
