### ISSUE TITLE
auto correct first letter of the subject to lower case

### ISSUE THREAD

**Issue by gtramontina** [kentcdodds/validate-commit-msg#37]
Hey there,
I found [these comments](https://github.com/kentcdodds/validate-commit-msg/blob/d8a2d19a387e070ab115683443c8b3397ee1aba0/index.js#L91-L99) in the source code:

>  // - auto correct first letter of the subject to lower case ?

We've recently adopted this format in a client and are using `git-cz` to help people with their commit messages. We are not yet enforcing the format, but most of the feedback are around people not following the "don't capitalize first letter" guideline.

I guess that having these options bring real value. 💭 ?

_ps: I can take a stab at it if you/more people find it valuable as well…_

**Comment by kentcdodds** [comment]
I think it'd be cool to be able to configure validate-commit-msg to auto-fix stuff. This would be opt-in functionality. Feel free to make a PR for that 😄
