### ISSUE TITLE
404 Error: Clicking on "LICENSE" Badge

### ISSUE THREAD

**Issue by oneezy** [kentcdodds/validate-commit-msg#53]
Just going through I noticed that your license badge link is going to a 404.
https://github.com/kentcdodds/validate-commit-msg/blob/master/other/LICENSE

**The culprit being:**
`https://github.com/kentcdodds/validate-commit-msg/blob/master/ `**`      OTHER      `**` /LICENSE`

**Comment by kentcdodds** [comment]
Cool, thanks for finding that. Could you [makeapullrequest.com](http://makeapullrequest.com)?

**Comment by oneezy** [comment]
On another note, trying **Attempt 1**, this raises a few questions..

By default `semantic-release` will push everything up to NPM, but since this is a Forked repo, that step isn't really necessary. Is semantic release smart enough to know the difference or is this something that the developer needs to be aware of?

I'm pretty fresh w/ semantic-release  so I'm not sure about these small intricacies.

**Comment by kentcdodds** [comment]
Hey @oneezy,
I apologize that you had these difficulties! I've just worked on things to make them a little more straightforward and hopefully improve your contributing experience!

Could you follow the new [Contributing guidelines](https://github.com/kentcdodds/validate-commit-msg/blob/master/CONTRIBUTING.md) and let me know whether that works better for you.

As with `semantic-release`, you should probably not be doing anything with that directly. Commitizen however should definitely work. Give it another shot and let me know if you have any additional trouble. Thanks!

**Comment by spirosikmd** [comment]
I hope it's ok I went through and fix that @oneezy!
