### ISSUE TITLE
Cannot find ".git" in parent directory

### ISSUE THREAD

**Issue by standy** [kentcdodds/validate-commit-msg#72]
Getting an error `Error: Cannot find file ./.git` because my package.json in subfolder from git root. Husky works fine with `find-parent-dir`: https://github.com/typicode/husky/blob/master/src/index.js#L29
Im pretty sure this package should do the same way

**Comment by kentcdodds** [comment]
Thanks for bringing this up. That solution sounds good to me! Want to [makeapullrequest.com](http://makeapullrequest.com)?

**Comment by standy** [comment]
Sure, I will do it
