### ISSUE TITLE
Make message format configurable

### ISSUE THREAD

**Issue by ntgn81** [kentcdodds/validate-commit-msg#76]
We have a bit different structure for commit message than what you have here, though I'd love to use this package as part of our workflow.

What do you think about making the message format configurable?

```js
{
  "messageFormat": "<type>(<scope>): <subject>" // default
}
```

Then we'd overwrite it with our own format, which is: `<type> <scope>: <subject>`

I can definitely try to make a PR if this sounds like a good idea.

Edit: Now that I think about it a bit more, having this might open a can of worm if the format has commas that conflict with scope separator, though that doesn't sound like a super common use case.

**Comment by kentcdodds** [comment]
Hi @ntgn81,
I'm not sure that I want to introduce more complexity into the tool. I would be willing to look at a pull request, but I wont personally be able to work on this.

You may also try looking at [`validate-commit`](https://github.com/willsoto/validate-commit).

**Comment by ntgn81** [comment]
@kentcdodds , that makes total sense. I'll take a look at `validate-commit`, thanks!

**Comment by AntonioRedondo** [comment]
Unfortunately [`validate-commit`](https://github.com/willsoto/validate-commit) doesn't implement custom regex validation either (though this could change soon).
