### ISSUE TITLE
Release as a default type?

### ISSUE THREAD

**Issue by naxhh** [kentcdodds/validate-commit-msg#78]
In my company we use this package in a few projects. We always end up hardcoding the types because we use `release` for commits that upgrade the package version or commits that produce a new shrinkwrap etc..

How do you feel about adding `release` as a default type?

**Comment by kentcdodds** [comment]
Hi @naxhh, this project [defaults to](https://github.com/kentcdodds/validate-commit-msg/blob/master/lib/validateMessage.js#L25) [`conventional-commit-types`](https://github.com/adjohnson916/conventional-commit-types). You might file an issue there, but I'm pretty sure that they'll probably want to stick to the standard. You could fork it and use your fork instead. See the docs on `types` :)

Good luck, and thanks :)

**Comment by naxhh** [comment]
```
Or you can specify the name of a module that exports types according to the conventional-commit-types spec, e.g. "types": "conventional-commit-types".
```

I didn't saw this when reviewing the readme. that solves my issue.

Thanks a lot for your time

**Comment by kentcdodds** [comment]
Sure thing!
